//
// Protocol buffers definition for Dadkvs Paxos Service
//
syntax = "proto3";
package dadkvs;

message PhaseOneRequest { // 1. Prepare
  int32 phase1config  = 1;
  int32 seqNum        = 2;
  int32 priority      = 3;
}

message PhaseOneReply { // 2. Promise
  int32 phase1config  = 1;
  int32 seqNum        = 2;
  bool  accepted      = 3;
  int32 phase1value   = 4; // Value left by previous leader in the same consensus
  int32 priority      = 5;
  bool  isDuplicated  = 6; // is value of phase2Req was already done on previous consensous
}

message PhaseTwoRequest { // 3. Accept
  int32 phase2config  = 1;
  int32 seqNum        = 2;
  int32 phase2value   = 3;
  int32 priority      = 4;
}

message PhaseTwoReply { // 4. Accepted
  int32 phase2config   = 1;
  int32 seqNum         = 2;
  bool  phase2accepted = 3;
  bool  isDuplicated   = 4; // is value of phase2Req was already done on previous consensous
}

message LearnRequest { // Inform Learners of Accepted transaction
  int32 learnconfig    = 1;
  int32 seqNum     = 2;
  int32 learnvalue     = 3;
  int32 priority = 4;
}

message LearnReply {  // Learners confirm recieving Accepted messages
  int32 learnconfig   = 1;
  int32 seqNum    = 2;
  bool  learnaccepted = 3;
}

service DadkvsPaxosService {
  rpc phaseOne (PhaseOneRequest) returns (PhaseOneReply);
  rpc phaseTwo (PhaseTwoRequest) returns (PhaseTwoReply);
  rpc learn (LearnRequest) returns (LearnReply);
}






