
package dadkvs.server;

import java.util.ArrayList;
import java.util.Iterator;

/* these imported classes are generated by the contract */
import dadkvs.DadkvsMain;
import dadkvs.DadkvsPaxos;
import dadkvs.DadkvsPaxosServiceGrpc;

import dadkvs.util.GenericResponseCollector;
import dadkvs.util.CollectorStreamObserver;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;

public class DadkvsPaxosServiceImpl extends DadkvsPaxosServiceGrpc.DadkvsPaxosServiceImplBase {

    DadkvsServerState server_state;

    public DadkvsPaxosServiceImpl(DadkvsServerState state) {
	    this.server_state = state;
    }


    @Override
    public void phaseOne(DadkvsPaxos.PhaseOneRequest request, StreamObserver<DadkvsPaxos.PhaseOneReply> responseObserver) {
        // for debug purposes
        System.out.println("Receive phase1 request: " + request);
        while (server_state.isFreezed){
            System.out.println("I am freezed ");
            try { wait ();}
            catch (InterruptedException e) {} // Ignore
        }
        DadkvsPaxos.PhaseOneReply response = server_state.paxos.handlePhaseOneReply(request.getPhase1Config(),
                                                                                    request.getSeqNum(),
                                                                                    request.getPriority());
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

    @Override
    public void phaseTwo(DadkvsPaxos.PhaseTwoRequest request, StreamObserver<DadkvsPaxos.PhaseTwoReply> responseObserver) {
        // for debug purposes
        System.out.println ("Receive phase two request: " + request);
        while (server_state.isFreezed){
            System.out.println("I am freezed ");
            try { wait ();}
            catch (InterruptedException e) {} // Ignore
        }
        DadkvsPaxos.PhaseTwoReply response = server_state.paxos.handlePhaseTwoReply(request.getPhase2Config(),
                                                                                    request.getSeqNum(),
                                                                                    request.getPhase2Value(),
                                                                                    request.getPriority());
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

    @Override
    public void learn(DadkvsPaxos.LearnRequest request, StreamObserver<DadkvsPaxos.LearnReply> responseObserver) {
        // for debug purposes
        System.out.println("Receive learn request: " + request);
        while (server_state.isFreezed){
            System.out.println("I am freezed ");
            try { wait ();}
            catch (InterruptedException e) {} // Ignore
        }
        // Save reqId and seqNum of this LearnRequest
        this.server_state.handleOrderID(request.getLearnvalue(), request.getSeqNum());

        DadkvsPaxos.LearnReply response = server_state.paxos.handleLearnReply(request.getLearnconfig(),
                                                                                    request.getSeqNum(),
                                                                                    request.getLearnvalue(),
                                                                                    request.getPriority());
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }
}
