
package dadkvs.server;



/* these imported classes are generated by the contract */
import dadkvs.DadkvsMain;
import dadkvs.DadkvsPaxos;
import dadkvs.DadkvsPaxosServiceGrpc;

import dadkvs.util.GenericResponseCollector;
import dadkvs.util.CollectorStreamObserver;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;

public class DadkvsPaxosServiceImpl extends DadkvsPaxosServiceGrpc.DadkvsPaxosServiceImplBase {

    DadkvsServerState server_state;

    public DadkvsPaxosServiceImpl(DadkvsServerState state) {
	    this.server_state = state;
    }


    @Override
    public void phaseOne(DadkvsPaxos.PhaseOneRequest request, StreamObserver<DadkvsPaxos.PhaseOneReply> responseObserver) {
        // for debug purposes
        System.out.println("Receive phase1 request: " + request);

        if ( this.server_state.isFreezed){
            this.server_state.freezeServer();
        }
        if (this.server_state.isDelayed){
			this.server_state.insertDelay();
		}

        DadkvsPaxos.PhaseOneReply response = server_state.acceptor.handlePhaseOneRequest(request.getPhase1Config(),
                                                                                    request.getSeqNum(),
                                                                                    request.getPriority());
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

    @Override
    public void phaseTwo(DadkvsPaxos.PhaseTwoRequest request, StreamObserver<DadkvsPaxos.PhaseTwoReply> responseObserver) {
        // for debug purposes
        System.out.println ("Receive phase two request: " + request);

        if ( this.server_state.isFreezed){
            this.server_state.freezeServer();
        }
        if (this.server_state.isDelayed){
			this.server_state.insertDelay();
		}

        DadkvsPaxos.PhaseTwoReply response = server_state.acceptor.handlePhaseTwoRequest(request.getPhase2Config(),
                                                                                    request.getSeqNum(),
                                                                                    request.getPhase2Value(),
                                                                                    request.getPriority());
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

    @Override
    public void learn(DadkvsPaxos.LearnRequest request, StreamObserver<DadkvsPaxos.LearnReply> responseObserver) {
        // for debug purposes
        System.out.println("Receive learn request: " + request);

        if ( this.server_state.isFreezed){
            this.server_state.freezeServer();
        }
        if (this.server_state.isDelayed){
			this.server_state.insertDelay();
		}

        DadkvsPaxos.LearnReply response = server_state.learner.handleLearnRequest(request.getLearnconfig(),
                                                                                    request.getSeqNum(),
                                                                                    request.getLearnvalue(),
                                                                                    request.getPriority());
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }
}
